export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR';
export const HOME_SCREEN = 'HOME_SCREEN';
export const ACCOUNT_SCREEN = 'ACCOUNT_SCREEN'; 